version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: BMC2081
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www/html
    command: ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html"]
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
